### ISSUE TITLE
JSON/YAML configuration documentation proposal

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/OSM-Bike-Ottawa-Tagging-Guide#19]
👍 @heatshear & @zzptichka for contributing so much.

I've been looking at the Markdown document and it's becoming more and more complex as we grow this.

My suggestion would be to move towards a more "human-friendly" format which will compile our defined schemas into a website and README.md.

Using this approach will also allow us to track changes easier since everything will be on multiple lines instead of the single line Markdown approach.

All the "special" formatting like linking the OSM wiki & Mapillary websites can be done in the same process, no need to add the websites directly to in the document.

## Using YAML

YAML is a `.yml` extension which can easily convert to JSON however it's a bit more flexible as a format (JSON is very strict and cannot include comments).

## YAML example of schema

For an example of Lanes, we would build these `.yml` or `.json` files into the `schema` folder, another process would grab all of these files and build a website and update the README.md with the changes (we can have a bot do that).

**Lanes.yml**

```yml
MUP:
  title:
    Paved Multi-Use Path (MUP)
  description:
    - Typically 3m wide, may be wider.
    - Intended for mixed bike and foot traffic.
  osm:
    - highway=path
    - surface=asphalt
  mapillary:
    - xvX6Bexu1gEE_H9KlfodLQ

Twinned_Path:
  title:
    Twinned Path
  description:
    - Typically >4.5 m wide.
    - Intended for separated bike and foot traffic
  osm:
    - highway=path
    - surface=asphalt
    - segregated=yes
  mapillary:
    - J5eakBF0yAOttLLsGtnkcg
```

## JSON

Similar to the YAML config, however more quotes and the JSON format is not as friendly to manually edit.

**Lanes.json**
```json
{
  "MUP": {
    "title": "Paved Multi-Use Path (MUP)",
    "description": [
      "Typically 3m wide, may be wider.",
      "Intended for mixed bike and foot traffic."
    ],
    "osm": [
      "highway=path",
      "surface=asphalt"
    ],
    "mapillary": [
      "xvX6Bexu1gEE_H9KlfodLQ"
    ]
  },
  "Twinned_Path": {
    "title": "Twinned Path",
    "description": [
      "Typically >4.5 m wide.",
      "Intended for separated bike and foot traffic"
    ],
    "osm": [
      "highway=path",
      "surface=asphalt",
      "segregated=yes"
    ],
    "mapillary": [
      "J5eakBF0yAOttLLsGtnkcg"
    ]
  }
}
```
